#https://magical-gumdrop-2a6118.netlify.app/
#https://r4sites-book.netlify.app/complete-end-to-end-example.html
#https://bookdown.org/yihui/blogdown/
library(blogdown)

serve_site()
blogdown::stop_server()



# clean the website generated by blogdown
rmarkdown::clean_site()

# build the website
blogdown::build_site()

# serve the website locally
blogdown::serve_site()

usethis::use_git()
usethis::use_github()